[tool.poetry]
name = "eniat"
version = "0.0.1"
description = "Experimental Neuroimaging Analaysis Tool"
authors = ["SungHo Lee <shlee@unc.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
